/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
var github_com_mwitkow_go$proto$validators_validator_pb = require('../github.com/mwitkow/go-proto-validators/validator_pb.js');
goog.object.extend(proto, github_com_mwitkow_go$proto$validators_validator_pb);
var deviced_model_pb = require('../deviced/model_pb.js');
goog.object.extend(proto, deviced_model_pb);
goog.exportSymbol('proto.ai.metathings.service.device.PushFrameToFlowRequest', null, global);
goog.exportSymbol('proto.ai.metathings.service.device.PushFrameToFlowRequest.Config', null, global);
goog.exportSymbol('proto.ai.metathings.service.device.PushFrameToFlowRequest.Ping', null, global);
goog.exportSymbol('proto.ai.metathings.service.device.PushFrameToFlowResponse', null, global);
goog.exportSymbol('proto.ai.metathings.service.device.PushFrameToFlowResponse.Ack', null, global);
goog.exportSymbol('proto.ai.metathings.service.device.PushFrameToFlowResponse.Config', null, global);
goog.exportSymbol('proto.ai.metathings.service.device.PushFrameToFlowResponse.Pong', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.ai.metathings.service.device.PushFrameToFlowRequest.oneofGroups_);
};
goog.inherits(proto.ai.metathings.service.device.PushFrameToFlowRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ai.metathings.service.device.PushFrameToFlowRequest.displayName = 'proto.ai.metathings.service.device.PushFrameToFlowRequest';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.oneofGroups_ = [[2,3,4]];

/**
 * @enum {number}
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.RequestCase = {
  REQUEST_NOT_SET: 0,
  CONFIG: 2,
  PING: 3,
  FRAME: 4
};

/**
 * @return {proto.ai.metathings.service.device.PushFrameToFlowRequest.RequestCase}
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.prototype.getRequestCase = function() {
  return /** @type {proto.ai.metathings.service.device.PushFrameToFlowRequest.RequestCase} */(jspb.Message.computeOneofCase(this, proto.ai.metathings.service.device.PushFrameToFlowRequest.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.ai.metathings.service.device.PushFrameToFlowRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai.metathings.service.device.PushFrameToFlowRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: (f = msg.getId()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    config: (f = msg.getConfig()) && proto.ai.metathings.service.device.PushFrameToFlowRequest.Config.toObject(includeInstance, f),
    ping: (f = msg.getPing()) && proto.ai.metathings.service.device.PushFrameToFlowRequest.Ping.toObject(includeInstance, f),
    frame: (f = msg.getFrame()) && deviced_model_pb.OpFrame.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai.metathings.service.device.PushFrameToFlowRequest}
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai.metathings.service.device.PushFrameToFlowRequest;
  return proto.ai.metathings.service.device.PushFrameToFlowRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai.metathings.service.device.PushFrameToFlowRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai.metathings.service.device.PushFrameToFlowRequest}
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    case 2:
      var value = new proto.ai.metathings.service.device.PushFrameToFlowRequest.Config;
      reader.readMessage(value,proto.ai.metathings.service.device.PushFrameToFlowRequest.Config.deserializeBinaryFromReader);
      msg.setConfig(value);
      break;
    case 3:
      var value = new proto.ai.metathings.service.device.PushFrameToFlowRequest.Ping;
      reader.readMessage(value,proto.ai.metathings.service.device.PushFrameToFlowRequest.Ping.deserializeBinaryFromReader);
      msg.setPing(value);
      break;
    case 4:
      var value = new deviced_model_pb.OpFrame;
      reader.readMessage(value,deviced_model_pb.OpFrame.deserializeBinaryFromReader);
      msg.setFrame(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai.metathings.service.device.PushFrameToFlowRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai.metathings.service.device.PushFrameToFlowRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getConfig();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.ai.metathings.service.device.PushFrameToFlowRequest.Config.serializeBinaryToWriter
    );
  }
  f = message.getPing();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.ai.metathings.service.device.PushFrameToFlowRequest.Ping.serializeBinaryToWriter
    );
  }
  f = message.getFrame();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      deviced_model_pb.OpFrame.serializeBinaryToWriter
    );
  }
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.Config = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ai.metathings.service.device.PushFrameToFlowRequest.Config, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ai.metathings.service.device.PushFrameToFlowRequest.Config.displayName = 'proto.ai.metathings.service.device.PushFrameToFlowRequest.Config';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.Config.prototype.toObject = function(opt_includeInstance) {
  return proto.ai.metathings.service.device.PushFrameToFlowRequest.Config.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai.metathings.service.device.PushFrameToFlowRequest.Config} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.Config.toObject = function(includeInstance, msg) {
  var f, obj = {
    flow: (f = msg.getFlow()) && deviced_model_pb.OpFlow.toObject(includeInstance, f),
    configAck: (f = msg.getConfigAck()) && google_protobuf_wrappers_pb.BoolValue.toObject(includeInstance, f),
    pushAck: (f = msg.getPushAck()) && google_protobuf_wrappers_pb.BoolValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai.metathings.service.device.PushFrameToFlowRequest.Config}
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.Config.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai.metathings.service.device.PushFrameToFlowRequest.Config;
  return proto.ai.metathings.service.device.PushFrameToFlowRequest.Config.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai.metathings.service.device.PushFrameToFlowRequest.Config} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai.metathings.service.device.PushFrameToFlowRequest.Config}
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.Config.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new deviced_model_pb.OpFlow;
      reader.readMessage(value,deviced_model_pb.OpFlow.deserializeBinaryFromReader);
      msg.setFlow(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.BoolValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.BoolValue.deserializeBinaryFromReader);
      msg.setConfigAck(value);
      break;
    case 3:
      var value = new google_protobuf_wrappers_pb.BoolValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.BoolValue.deserializeBinaryFromReader);
      msg.setPushAck(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.Config.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai.metathings.service.device.PushFrameToFlowRequest.Config.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai.metathings.service.device.PushFrameToFlowRequest.Config} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.Config.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFlow();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      deviced_model_pb.OpFlow.serializeBinaryToWriter
    );
  }
  f = message.getConfigAck();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.BoolValue.serializeBinaryToWriter
    );
  }
  f = message.getPushAck();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_wrappers_pb.BoolValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional ai.metathings.service.deviced.OpFlow flow = 1;
 * @return {?proto.ai.metathings.service.deviced.OpFlow}
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.Config.prototype.getFlow = function() {
  return /** @type{?proto.ai.metathings.service.deviced.OpFlow} */ (
    jspb.Message.getWrapperField(this, deviced_model_pb.OpFlow, 1));
};


/** @param {?proto.ai.metathings.service.deviced.OpFlow|undefined} value */
proto.ai.metathings.service.device.PushFrameToFlowRequest.Config.prototype.setFlow = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.ai.metathings.service.device.PushFrameToFlowRequest.Config.prototype.clearFlow = function() {
  this.setFlow(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.Config.prototype.hasFlow = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.BoolValue config_ack = 2;
 * @return {?proto.google.protobuf.BoolValue}
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.Config.prototype.getConfigAck = function() {
  return /** @type{?proto.google.protobuf.BoolValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.BoolValue, 2));
};


/** @param {?proto.google.protobuf.BoolValue|undefined} value */
proto.ai.metathings.service.device.PushFrameToFlowRequest.Config.prototype.setConfigAck = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.ai.metathings.service.device.PushFrameToFlowRequest.Config.prototype.clearConfigAck = function() {
  this.setConfigAck(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.Config.prototype.hasConfigAck = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.BoolValue push_ack = 3;
 * @return {?proto.google.protobuf.BoolValue}
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.Config.prototype.getPushAck = function() {
  return /** @type{?proto.google.protobuf.BoolValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.BoolValue, 3));
};


/** @param {?proto.google.protobuf.BoolValue|undefined} value */
proto.ai.metathings.service.device.PushFrameToFlowRequest.Config.prototype.setPushAck = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.ai.metathings.service.device.PushFrameToFlowRequest.Config.prototype.clearPushAck = function() {
  this.setPushAck(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.Config.prototype.hasPushAck = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.Ping = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ai.metathings.service.device.PushFrameToFlowRequest.Ping, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ai.metathings.service.device.PushFrameToFlowRequest.Ping.displayName = 'proto.ai.metathings.service.device.PushFrameToFlowRequest.Ping';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.Ping.prototype.toObject = function(opt_includeInstance) {
  return proto.ai.metathings.service.device.PushFrameToFlowRequest.Ping.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai.metathings.service.device.PushFrameToFlowRequest.Ping} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.Ping.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai.metathings.service.device.PushFrameToFlowRequest.Ping}
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.Ping.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai.metathings.service.device.PushFrameToFlowRequest.Ping;
  return proto.ai.metathings.service.device.PushFrameToFlowRequest.Ping.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai.metathings.service.device.PushFrameToFlowRequest.Ping} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai.metathings.service.device.PushFrameToFlowRequest.Ping}
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.Ping.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.Ping.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai.metathings.service.device.PushFrameToFlowRequest.Ping.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai.metathings.service.device.PushFrameToFlowRequest.Ping} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.Ping.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


/**
 * optional google.protobuf.StringValue id = 1;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.prototype.getId = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 1));
};


/** @param {?proto.google.protobuf.StringValue|undefined} value */
proto.ai.metathings.service.device.PushFrameToFlowRequest.prototype.setId = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.ai.metathings.service.device.PushFrameToFlowRequest.prototype.clearId = function() {
  this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.prototype.hasId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Config config = 2;
 * @return {?proto.ai.metathings.service.device.PushFrameToFlowRequest.Config}
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.prototype.getConfig = function() {
  return /** @type{?proto.ai.metathings.service.device.PushFrameToFlowRequest.Config} */ (
    jspb.Message.getWrapperField(this, proto.ai.metathings.service.device.PushFrameToFlowRequest.Config, 2));
};


/** @param {?proto.ai.metathings.service.device.PushFrameToFlowRequest.Config|undefined} value */
proto.ai.metathings.service.device.PushFrameToFlowRequest.prototype.setConfig = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.ai.metathings.service.device.PushFrameToFlowRequest.oneofGroups_[0], value);
};


proto.ai.metathings.service.device.PushFrameToFlowRequest.prototype.clearConfig = function() {
  this.setConfig(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.prototype.hasConfig = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Ping ping = 3;
 * @return {?proto.ai.metathings.service.device.PushFrameToFlowRequest.Ping}
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.prototype.getPing = function() {
  return /** @type{?proto.ai.metathings.service.device.PushFrameToFlowRequest.Ping} */ (
    jspb.Message.getWrapperField(this, proto.ai.metathings.service.device.PushFrameToFlowRequest.Ping, 3));
};


/** @param {?proto.ai.metathings.service.device.PushFrameToFlowRequest.Ping|undefined} value */
proto.ai.metathings.service.device.PushFrameToFlowRequest.prototype.setPing = function(value) {
  jspb.Message.setOneofWrapperField(this, 3, proto.ai.metathings.service.device.PushFrameToFlowRequest.oneofGroups_[0], value);
};


proto.ai.metathings.service.device.PushFrameToFlowRequest.prototype.clearPing = function() {
  this.setPing(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.prototype.hasPing = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional ai.metathings.service.deviced.OpFrame frame = 4;
 * @return {?proto.ai.metathings.service.deviced.OpFrame}
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.prototype.getFrame = function() {
  return /** @type{?proto.ai.metathings.service.deviced.OpFrame} */ (
    jspb.Message.getWrapperField(this, deviced_model_pb.OpFrame, 4));
};


/** @param {?proto.ai.metathings.service.deviced.OpFrame|undefined} value */
proto.ai.metathings.service.device.PushFrameToFlowRequest.prototype.setFrame = function(value) {
  jspb.Message.setOneofWrapperField(this, 4, proto.ai.metathings.service.device.PushFrameToFlowRequest.oneofGroups_[0], value);
};


proto.ai.metathings.service.device.PushFrameToFlowRequest.prototype.clearFrame = function() {
  this.setFrame(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ai.metathings.service.device.PushFrameToFlowRequest.prototype.hasFrame = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.ai.metathings.service.device.PushFrameToFlowResponse.oneofGroups_);
};
goog.inherits(proto.ai.metathings.service.device.PushFrameToFlowResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ai.metathings.service.device.PushFrameToFlowResponse.displayName = 'proto.ai.metathings.service.device.PushFrameToFlowResponse';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.oneofGroups_ = [[2,3,4]];

/**
 * @enum {number}
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.ResponseCase = {
  RESPONSE_NOT_SET: 0,
  CONFIG: 2,
  PONG: 3,
  ACK: 4
};

/**
 * @return {proto.ai.metathings.service.device.PushFrameToFlowResponse.ResponseCase}
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.prototype.getResponseCase = function() {
  return /** @type {proto.ai.metathings.service.device.PushFrameToFlowResponse.ResponseCase} */(jspb.Message.computeOneofCase(this, proto.ai.metathings.service.device.PushFrameToFlowResponse.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.ai.metathings.service.device.PushFrameToFlowResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai.metathings.service.device.PushFrameToFlowResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    config: (f = msg.getConfig()) && proto.ai.metathings.service.device.PushFrameToFlowResponse.Config.toObject(includeInstance, f),
    pong: (f = msg.getPong()) && proto.ai.metathings.service.device.PushFrameToFlowResponse.Pong.toObject(includeInstance, f),
    ack: (f = msg.getAck()) && proto.ai.metathings.service.device.PushFrameToFlowResponse.Ack.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai.metathings.service.device.PushFrameToFlowResponse}
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai.metathings.service.device.PushFrameToFlowResponse;
  return proto.ai.metathings.service.device.PushFrameToFlowResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai.metathings.service.device.PushFrameToFlowResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai.metathings.service.device.PushFrameToFlowResponse}
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = new proto.ai.metathings.service.device.PushFrameToFlowResponse.Config;
      reader.readMessage(value,proto.ai.metathings.service.device.PushFrameToFlowResponse.Config.deserializeBinaryFromReader);
      msg.setConfig(value);
      break;
    case 3:
      var value = new proto.ai.metathings.service.device.PushFrameToFlowResponse.Pong;
      reader.readMessage(value,proto.ai.metathings.service.device.PushFrameToFlowResponse.Pong.deserializeBinaryFromReader);
      msg.setPong(value);
      break;
    case 4:
      var value = new proto.ai.metathings.service.device.PushFrameToFlowResponse.Ack;
      reader.readMessage(value,proto.ai.metathings.service.device.PushFrameToFlowResponse.Ack.deserializeBinaryFromReader);
      msg.setAck(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai.metathings.service.device.PushFrameToFlowResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai.metathings.service.device.PushFrameToFlowResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getConfig();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.ai.metathings.service.device.PushFrameToFlowResponse.Config.serializeBinaryToWriter
    );
  }
  f = message.getPong();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.ai.metathings.service.device.PushFrameToFlowResponse.Pong.serializeBinaryToWriter
    );
  }
  f = message.getAck();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.ai.metathings.service.device.PushFrameToFlowResponse.Ack.serializeBinaryToWriter
    );
  }
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.Config = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ai.metathings.service.device.PushFrameToFlowResponse.Config, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ai.metathings.service.device.PushFrameToFlowResponse.Config.displayName = 'proto.ai.metathings.service.device.PushFrameToFlowResponse.Config';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.Config.prototype.toObject = function(opt_includeInstance) {
  return proto.ai.metathings.service.device.PushFrameToFlowResponse.Config.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai.metathings.service.device.PushFrameToFlowResponse.Config} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.Config.toObject = function(includeInstance, msg) {
  var f, obj = {
    session: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai.metathings.service.device.PushFrameToFlowResponse.Config}
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.Config.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai.metathings.service.device.PushFrameToFlowResponse.Config;
  return proto.ai.metathings.service.device.PushFrameToFlowResponse.Config.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai.metathings.service.device.PushFrameToFlowResponse.Config} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai.metathings.service.device.PushFrameToFlowResponse.Config}
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.Config.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSession(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.Config.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai.metathings.service.device.PushFrameToFlowResponse.Config.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai.metathings.service.device.PushFrameToFlowResponse.Config} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.Config.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSession();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string session = 1;
 * @return {string}
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.Config.prototype.getSession = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.ai.metathings.service.device.PushFrameToFlowResponse.Config.prototype.setSession = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.Ack = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ai.metathings.service.device.PushFrameToFlowResponse.Ack, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ai.metathings.service.device.PushFrameToFlowResponse.Ack.displayName = 'proto.ai.metathings.service.device.PushFrameToFlowResponse.Ack';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.Ack.prototype.toObject = function(opt_includeInstance) {
  return proto.ai.metathings.service.device.PushFrameToFlowResponse.Ack.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai.metathings.service.device.PushFrameToFlowResponse.Ack} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.Ack.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai.metathings.service.device.PushFrameToFlowResponse.Ack}
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.Ack.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai.metathings.service.device.PushFrameToFlowResponse.Ack;
  return proto.ai.metathings.service.device.PushFrameToFlowResponse.Ack.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai.metathings.service.device.PushFrameToFlowResponse.Ack} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai.metathings.service.device.PushFrameToFlowResponse.Ack}
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.Ack.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.Ack.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai.metathings.service.device.PushFrameToFlowResponse.Ack.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai.metathings.service.device.PushFrameToFlowResponse.Ack} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.Ack.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.Pong = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ai.metathings.service.device.PushFrameToFlowResponse.Pong, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ai.metathings.service.device.PushFrameToFlowResponse.Pong.displayName = 'proto.ai.metathings.service.device.PushFrameToFlowResponse.Pong';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.Pong.prototype.toObject = function(opt_includeInstance) {
  return proto.ai.metathings.service.device.PushFrameToFlowResponse.Pong.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai.metathings.service.device.PushFrameToFlowResponse.Pong} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.Pong.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai.metathings.service.device.PushFrameToFlowResponse.Pong}
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.Pong.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai.metathings.service.device.PushFrameToFlowResponse.Pong;
  return proto.ai.metathings.service.device.PushFrameToFlowResponse.Pong.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai.metathings.service.device.PushFrameToFlowResponse.Pong} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai.metathings.service.device.PushFrameToFlowResponse.Pong}
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.Pong.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.Pong.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai.metathings.service.device.PushFrameToFlowResponse.Pong.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai.metathings.service.device.PushFrameToFlowResponse.Pong} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.Pong.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.ai.metathings.service.device.PushFrameToFlowResponse.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Config config = 2;
 * @return {?proto.ai.metathings.service.device.PushFrameToFlowResponse.Config}
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.prototype.getConfig = function() {
  return /** @type{?proto.ai.metathings.service.device.PushFrameToFlowResponse.Config} */ (
    jspb.Message.getWrapperField(this, proto.ai.metathings.service.device.PushFrameToFlowResponse.Config, 2));
};


/** @param {?proto.ai.metathings.service.device.PushFrameToFlowResponse.Config|undefined} value */
proto.ai.metathings.service.device.PushFrameToFlowResponse.prototype.setConfig = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.ai.metathings.service.device.PushFrameToFlowResponse.oneofGroups_[0], value);
};


proto.ai.metathings.service.device.PushFrameToFlowResponse.prototype.clearConfig = function() {
  this.setConfig(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.prototype.hasConfig = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Pong pong = 3;
 * @return {?proto.ai.metathings.service.device.PushFrameToFlowResponse.Pong}
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.prototype.getPong = function() {
  return /** @type{?proto.ai.metathings.service.device.PushFrameToFlowResponse.Pong} */ (
    jspb.Message.getWrapperField(this, proto.ai.metathings.service.device.PushFrameToFlowResponse.Pong, 3));
};


/** @param {?proto.ai.metathings.service.device.PushFrameToFlowResponse.Pong|undefined} value */
proto.ai.metathings.service.device.PushFrameToFlowResponse.prototype.setPong = function(value) {
  jspb.Message.setOneofWrapperField(this, 3, proto.ai.metathings.service.device.PushFrameToFlowResponse.oneofGroups_[0], value);
};


proto.ai.metathings.service.device.PushFrameToFlowResponse.prototype.clearPong = function() {
  this.setPong(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.prototype.hasPong = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Ack ack = 4;
 * @return {?proto.ai.metathings.service.device.PushFrameToFlowResponse.Ack}
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.prototype.getAck = function() {
  return /** @type{?proto.ai.metathings.service.device.PushFrameToFlowResponse.Ack} */ (
    jspb.Message.getWrapperField(this, proto.ai.metathings.service.device.PushFrameToFlowResponse.Ack, 4));
};


/** @param {?proto.ai.metathings.service.device.PushFrameToFlowResponse.Ack|undefined} value */
proto.ai.metathings.service.device.PushFrameToFlowResponse.prototype.setAck = function(value) {
  jspb.Message.setOneofWrapperField(this, 4, proto.ai.metathings.service.device.PushFrameToFlowResponse.oneofGroups_[0], value);
};


proto.ai.metathings.service.device.PushFrameToFlowResponse.prototype.clearAck = function() {
  this.setAck(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ai.metathings.service.device.PushFrameToFlowResponse.prototype.hasAck = function() {
  return jspb.Message.getField(this, 4) != null;
};


goog.object.extend(exports, proto.ai.metathings.service.device);
