/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
var github_com_mwitkow_go$proto$validators_validator_pb = require('../github.com/mwitkow/go-proto-validators/validator_pb.js');
goog.object.extend(proto, github_com_mwitkow_go$proto$validators_validator_pb);
var deviced_model_pb = require('../deviced/model_pb.js');
goog.object.extend(proto, deviced_model_pb);
goog.exportSymbol('proto.ai.metathings.service.deviced.PushFrameToFlowRequest', null, global);
goog.exportSymbol('proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config', null, global);
goog.exportSymbol('proto.ai.metathings.service.deviced.PushFrameToFlowResponse', null, global);
goog.exportSymbol('proto.ai.metathings.service.deviced.PushFrameToFlowResponse.Ack', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai.metathings.service.deviced.PushFrameToFlowRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.ai.metathings.service.deviced.PushFrameToFlowRequest.oneofGroups_);
};
goog.inherits(proto.ai.metathings.service.deviced.PushFrameToFlowRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ai.metathings.service.deviced.PushFrameToFlowRequest.displayName = 'proto.ai.metathings.service.deviced.PushFrameToFlowRequest';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.ai.metathings.service.deviced.PushFrameToFlowRequest.oneofGroups_ = [[2,3]];

/**
 * @enum {number}
 */
proto.ai.metathings.service.deviced.PushFrameToFlowRequest.RequestCase = {
  REQUEST_NOT_SET: 0,
  CONFIG: 2,
  FRAME: 3
};

/**
 * @return {proto.ai.metathings.service.deviced.PushFrameToFlowRequest.RequestCase}
 */
proto.ai.metathings.service.deviced.PushFrameToFlowRequest.prototype.getRequestCase = function() {
  return /** @type {proto.ai.metathings.service.deviced.PushFrameToFlowRequest.RequestCase} */(jspb.Message.computeOneofCase(this, proto.ai.metathings.service.deviced.PushFrameToFlowRequest.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai.metathings.service.deviced.PushFrameToFlowRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.ai.metathings.service.deviced.PushFrameToFlowRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai.metathings.service.deviced.PushFrameToFlowRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.metathings.service.deviced.PushFrameToFlowRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: (f = msg.getId()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    config: (f = msg.getConfig()) && proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config.toObject(includeInstance, f),
    frame: (f = msg.getFrame()) && deviced_model_pb.OpFrame.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai.metathings.service.deviced.PushFrameToFlowRequest}
 */
proto.ai.metathings.service.deviced.PushFrameToFlowRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai.metathings.service.deviced.PushFrameToFlowRequest;
  return proto.ai.metathings.service.deviced.PushFrameToFlowRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai.metathings.service.deviced.PushFrameToFlowRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai.metathings.service.deviced.PushFrameToFlowRequest}
 */
proto.ai.metathings.service.deviced.PushFrameToFlowRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    case 2:
      var value = new proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config;
      reader.readMessage(value,proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config.deserializeBinaryFromReader);
      msg.setConfig(value);
      break;
    case 3:
      var value = new deviced_model_pb.OpFrame;
      reader.readMessage(value,deviced_model_pb.OpFrame.deserializeBinaryFromReader);
      msg.setFrame(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai.metathings.service.deviced.PushFrameToFlowRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai.metathings.service.deviced.PushFrameToFlowRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai.metathings.service.deviced.PushFrameToFlowRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.metathings.service.deviced.PushFrameToFlowRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getConfig();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config.serializeBinaryToWriter
    );
  }
  f = message.getFrame();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      deviced_model_pb.OpFrame.serializeBinaryToWriter
    );
  }
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config.displayName = 'proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config.prototype.toObject = function(opt_includeInstance) {
  return proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config.toObject = function(includeInstance, msg) {
  var f, obj = {
    device: (f = msg.getDevice()) && deviced_model_pb.OpDevice.toObject(includeInstance, f),
    configAck: (f = msg.getConfigAck()) && google_protobuf_wrappers_pb.BoolValue.toObject(includeInstance, f),
    pushAck: (f = msg.getPushAck()) && google_protobuf_wrappers_pb.BoolValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config}
 */
proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config;
  return proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config}
 */
proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new deviced_model_pb.OpDevice;
      reader.readMessage(value,deviced_model_pb.OpDevice.deserializeBinaryFromReader);
      msg.setDevice(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.BoolValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.BoolValue.deserializeBinaryFromReader);
      msg.setConfigAck(value);
      break;
    case 3:
      var value = new google_protobuf_wrappers_pb.BoolValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.BoolValue.deserializeBinaryFromReader);
      msg.setPushAck(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDevice();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      deviced_model_pb.OpDevice.serializeBinaryToWriter
    );
  }
  f = message.getConfigAck();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.BoolValue.serializeBinaryToWriter
    );
  }
  f = message.getPushAck();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_wrappers_pb.BoolValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional OpDevice device = 1;
 * @return {?proto.ai.metathings.service.deviced.OpDevice}
 */
proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config.prototype.getDevice = function() {
  return /** @type{?proto.ai.metathings.service.deviced.OpDevice} */ (
    jspb.Message.getWrapperField(this, deviced_model_pb.OpDevice, 1));
};


/** @param {?proto.ai.metathings.service.deviced.OpDevice|undefined} value */
proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config.prototype.setDevice = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config.prototype.clearDevice = function() {
  this.setDevice(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config.prototype.hasDevice = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.BoolValue config_ack = 2;
 * @return {?proto.google.protobuf.BoolValue}
 */
proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config.prototype.getConfigAck = function() {
  return /** @type{?proto.google.protobuf.BoolValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.BoolValue, 2));
};


/** @param {?proto.google.protobuf.BoolValue|undefined} value */
proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config.prototype.setConfigAck = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config.prototype.clearConfigAck = function() {
  this.setConfigAck(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config.prototype.hasConfigAck = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.BoolValue push_ack = 3;
 * @return {?proto.google.protobuf.BoolValue}
 */
proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config.prototype.getPushAck = function() {
  return /** @type{?proto.google.protobuf.BoolValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.BoolValue, 3));
};


/** @param {?proto.google.protobuf.BoolValue|undefined} value */
proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config.prototype.setPushAck = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config.prototype.clearPushAck = function() {
  this.setPushAck(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config.prototype.hasPushAck = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.StringValue id = 1;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.ai.metathings.service.deviced.PushFrameToFlowRequest.prototype.getId = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 1));
};


/** @param {?proto.google.protobuf.StringValue|undefined} value */
proto.ai.metathings.service.deviced.PushFrameToFlowRequest.prototype.setId = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.ai.metathings.service.deviced.PushFrameToFlowRequest.prototype.clearId = function() {
  this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ai.metathings.service.deviced.PushFrameToFlowRequest.prototype.hasId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Config config = 2;
 * @return {?proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config}
 */
proto.ai.metathings.service.deviced.PushFrameToFlowRequest.prototype.getConfig = function() {
  return /** @type{?proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config} */ (
    jspb.Message.getWrapperField(this, proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config, 2));
};


/** @param {?proto.ai.metathings.service.deviced.PushFrameToFlowRequest.Config|undefined} value */
proto.ai.metathings.service.deviced.PushFrameToFlowRequest.prototype.setConfig = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.ai.metathings.service.deviced.PushFrameToFlowRequest.oneofGroups_[0], value);
};


proto.ai.metathings.service.deviced.PushFrameToFlowRequest.prototype.clearConfig = function() {
  this.setConfig(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ai.metathings.service.deviced.PushFrameToFlowRequest.prototype.hasConfig = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional OpFrame frame = 3;
 * @return {?proto.ai.metathings.service.deviced.OpFrame}
 */
proto.ai.metathings.service.deviced.PushFrameToFlowRequest.prototype.getFrame = function() {
  return /** @type{?proto.ai.metathings.service.deviced.OpFrame} */ (
    jspb.Message.getWrapperField(this, deviced_model_pb.OpFrame, 3));
};


/** @param {?proto.ai.metathings.service.deviced.OpFrame|undefined} value */
proto.ai.metathings.service.deviced.PushFrameToFlowRequest.prototype.setFrame = function(value) {
  jspb.Message.setOneofWrapperField(this, 3, proto.ai.metathings.service.deviced.PushFrameToFlowRequest.oneofGroups_[0], value);
};


proto.ai.metathings.service.deviced.PushFrameToFlowRequest.prototype.clearFrame = function() {
  this.setFrame(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ai.metathings.service.deviced.PushFrameToFlowRequest.prototype.hasFrame = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai.metathings.service.deviced.PushFrameToFlowResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.ai.metathings.service.deviced.PushFrameToFlowResponse.oneofGroups_);
};
goog.inherits(proto.ai.metathings.service.deviced.PushFrameToFlowResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ai.metathings.service.deviced.PushFrameToFlowResponse.displayName = 'proto.ai.metathings.service.deviced.PushFrameToFlowResponse';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.ai.metathings.service.deviced.PushFrameToFlowResponse.oneofGroups_ = [[2]];

/**
 * @enum {number}
 */
proto.ai.metathings.service.deviced.PushFrameToFlowResponse.ResponseCase = {
  RESPONSE_NOT_SET: 0,
  ACK: 2
};

/**
 * @return {proto.ai.metathings.service.deviced.PushFrameToFlowResponse.ResponseCase}
 */
proto.ai.metathings.service.deviced.PushFrameToFlowResponse.prototype.getResponseCase = function() {
  return /** @type {proto.ai.metathings.service.deviced.PushFrameToFlowResponse.ResponseCase} */(jspb.Message.computeOneofCase(this, proto.ai.metathings.service.deviced.PushFrameToFlowResponse.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai.metathings.service.deviced.PushFrameToFlowResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.ai.metathings.service.deviced.PushFrameToFlowResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai.metathings.service.deviced.PushFrameToFlowResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.metathings.service.deviced.PushFrameToFlowResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    ack: (f = msg.getAck()) && proto.ai.metathings.service.deviced.PushFrameToFlowResponse.Ack.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai.metathings.service.deviced.PushFrameToFlowResponse}
 */
proto.ai.metathings.service.deviced.PushFrameToFlowResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai.metathings.service.deviced.PushFrameToFlowResponse;
  return proto.ai.metathings.service.deviced.PushFrameToFlowResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai.metathings.service.deviced.PushFrameToFlowResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai.metathings.service.deviced.PushFrameToFlowResponse}
 */
proto.ai.metathings.service.deviced.PushFrameToFlowResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = new proto.ai.metathings.service.deviced.PushFrameToFlowResponse.Ack;
      reader.readMessage(value,proto.ai.metathings.service.deviced.PushFrameToFlowResponse.Ack.deserializeBinaryFromReader);
      msg.setAck(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai.metathings.service.deviced.PushFrameToFlowResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai.metathings.service.deviced.PushFrameToFlowResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai.metathings.service.deviced.PushFrameToFlowResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.metathings.service.deviced.PushFrameToFlowResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAck();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.ai.metathings.service.deviced.PushFrameToFlowResponse.Ack.serializeBinaryToWriter
    );
  }
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai.metathings.service.deviced.PushFrameToFlowResponse.Ack = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ai.metathings.service.deviced.PushFrameToFlowResponse.Ack, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ai.metathings.service.deviced.PushFrameToFlowResponse.Ack.displayName = 'proto.ai.metathings.service.deviced.PushFrameToFlowResponse.Ack';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai.metathings.service.deviced.PushFrameToFlowResponse.Ack.prototype.toObject = function(opt_includeInstance) {
  return proto.ai.metathings.service.deviced.PushFrameToFlowResponse.Ack.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai.metathings.service.deviced.PushFrameToFlowResponse.Ack} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.metathings.service.deviced.PushFrameToFlowResponse.Ack.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai.metathings.service.deviced.PushFrameToFlowResponse.Ack}
 */
proto.ai.metathings.service.deviced.PushFrameToFlowResponse.Ack.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai.metathings.service.deviced.PushFrameToFlowResponse.Ack;
  return proto.ai.metathings.service.deviced.PushFrameToFlowResponse.Ack.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai.metathings.service.deviced.PushFrameToFlowResponse.Ack} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai.metathings.service.deviced.PushFrameToFlowResponse.Ack}
 */
proto.ai.metathings.service.deviced.PushFrameToFlowResponse.Ack.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai.metathings.service.deviced.PushFrameToFlowResponse.Ack.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai.metathings.service.deviced.PushFrameToFlowResponse.Ack.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai.metathings.service.deviced.PushFrameToFlowResponse.Ack} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.metathings.service.deviced.PushFrameToFlowResponse.Ack.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.ai.metathings.service.deviced.PushFrameToFlowResponse.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.ai.metathings.service.deviced.PushFrameToFlowResponse.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Ack ack = 2;
 * @return {?proto.ai.metathings.service.deviced.PushFrameToFlowResponse.Ack}
 */
proto.ai.metathings.service.deviced.PushFrameToFlowResponse.prototype.getAck = function() {
  return /** @type{?proto.ai.metathings.service.deviced.PushFrameToFlowResponse.Ack} */ (
    jspb.Message.getWrapperField(this, proto.ai.metathings.service.deviced.PushFrameToFlowResponse.Ack, 2));
};


/** @param {?proto.ai.metathings.service.deviced.PushFrameToFlowResponse.Ack|undefined} value */
proto.ai.metathings.service.deviced.PushFrameToFlowResponse.prototype.setAck = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.ai.metathings.service.deviced.PushFrameToFlowResponse.oneofGroups_[0], value);
};


proto.ai.metathings.service.deviced.PushFrameToFlowResponse.prototype.clearAck = function() {
  this.setAck(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ai.metathings.service.deviced.PushFrameToFlowResponse.prototype.hasAck = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.ai.metathings.service.deviced);
