/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
var identityd2_create_domain_pb = require('../identityd2/create_domain_pb.js');
goog.object.extend(proto, identityd2_create_domain_pb);
var identityd2_delete_domain_pb = require('../identityd2/delete_domain_pb.js');
goog.object.extend(proto, identityd2_delete_domain_pb);
var identityd2_patch_domain_pb = require('../identityd2/patch_domain_pb.js');
goog.object.extend(proto, identityd2_patch_domain_pb);
var identityd2_get_domain_pb = require('../identityd2/get_domain_pb.js');
goog.object.extend(proto, identityd2_get_domain_pb);
var identityd2_list_domains_pb = require('../identityd2/list_domains_pb.js');
goog.object.extend(proto, identityd2_list_domains_pb);
var identityd2_create_action_pb = require('../identityd2/create_action_pb.js');
goog.object.extend(proto, identityd2_create_action_pb);
var identityd2_delete_action_pb = require('../identityd2/delete_action_pb.js');
goog.object.extend(proto, identityd2_delete_action_pb);
var identityd2_patch_action_pb = require('../identityd2/patch_action_pb.js');
goog.object.extend(proto, identityd2_patch_action_pb);
var identityd2_get_action_pb = require('../identityd2/get_action_pb.js');
goog.object.extend(proto, identityd2_get_action_pb);
var identityd2_list_actions_pb = require('../identityd2/list_actions_pb.js');
goog.object.extend(proto, identityd2_list_actions_pb);
var identityd2_create_role_pb = require('../identityd2/create_role_pb.js');
goog.object.extend(proto, identityd2_create_role_pb);
var identityd2_delete_role_pb = require('../identityd2/delete_role_pb.js');
goog.object.extend(proto, identityd2_delete_role_pb);
var identityd2_patch_role_pb = require('../identityd2/patch_role_pb.js');
goog.object.extend(proto, identityd2_patch_role_pb);
var identityd2_get_role_pb = require('../identityd2/get_role_pb.js');
goog.object.extend(proto, identityd2_get_role_pb);
var identityd2_list_roles_pb = require('../identityd2/list_roles_pb.js');
goog.object.extend(proto, identityd2_list_roles_pb);
var identityd2_list_roles_for_entity_pb = require('../identityd2/list_roles_for_entity_pb.js');
goog.object.extend(proto, identityd2_list_roles_for_entity_pb);
var identityd2_add_action_to_role_pb = require('../identityd2/add_action_to_role_pb.js');
goog.object.extend(proto, identityd2_add_action_to_role_pb);
var identityd2_remove_action_from_role_pb = require('../identityd2/remove_action_from_role_pb.js');
goog.object.extend(proto, identityd2_remove_action_from_role_pb);
var identityd2_create_entity_pb = require('../identityd2/create_entity_pb.js');
goog.object.extend(proto, identityd2_create_entity_pb);
var identityd2_delete_entity_pb = require('../identityd2/delete_entity_pb.js');
goog.object.extend(proto, identityd2_delete_entity_pb);
var identityd2_patch_entity_pb = require('../identityd2/patch_entity_pb.js');
goog.object.extend(proto, identityd2_patch_entity_pb);
var identityd2_get_entity_pb = require('../identityd2/get_entity_pb.js');
goog.object.extend(proto, identityd2_get_entity_pb);
var identityd2_list_entities_pb = require('../identityd2/list_entities_pb.js');
goog.object.extend(proto, identityd2_list_entities_pb);
var identityd2_show_entity_pb = require('../identityd2/show_entity_pb.js');
goog.object.extend(proto, identityd2_show_entity_pb);
var identityd2_add_role_to_entity_pb = require('../identityd2/add_role_to_entity_pb.js');
goog.object.extend(proto, identityd2_add_role_to_entity_pb);
var identityd2_remove_role_from_entity_pb = require('../identityd2/remove_role_from_entity_pb.js');
goog.object.extend(proto, identityd2_remove_role_from_entity_pb);
var identityd2_add_entity_to_domain_pb = require('../identityd2/add_entity_to_domain_pb.js');
goog.object.extend(proto, identityd2_add_entity_to_domain_pb);
var identityd2_remove_entity_from_domain_pb = require('../identityd2/remove_entity_from_domain_pb.js');
goog.object.extend(proto, identityd2_remove_entity_from_domain_pb);
var identityd2_create_group_pb = require('../identityd2/create_group_pb.js');
goog.object.extend(proto, identityd2_create_group_pb);
var identityd2_delete_group_pb = require('../identityd2/delete_group_pb.js');
goog.object.extend(proto, identityd2_delete_group_pb);
var identityd2_patch_group_pb = require('../identityd2/patch_group_pb.js');
goog.object.extend(proto, identityd2_patch_group_pb);
var identityd2_get_group_pb = require('../identityd2/get_group_pb.js');
goog.object.extend(proto, identityd2_get_group_pb);
var identityd2_list_groups_pb = require('../identityd2/list_groups_pb.js');
goog.object.extend(proto, identityd2_list_groups_pb);
var identityd2_list_groups_for_subject_pb = require('../identityd2/list_groups_for_subject_pb.js');
goog.object.extend(proto, identityd2_list_groups_for_subject_pb);
var identityd2_list_groups_for_object_pb = require('../identityd2/list_groups_for_object_pb.js');
goog.object.extend(proto, identityd2_list_groups_for_object_pb);
var identityd2_show_groups_pb = require('../identityd2/show_groups_pb.js');
goog.object.extend(proto, identityd2_show_groups_pb);
var identityd2_add_role_to_group_pb = require('../identityd2/add_role_to_group_pb.js');
goog.object.extend(proto, identityd2_add_role_to_group_pb);
var identityd2_remove_role_from_group_pb = require('../identityd2/remove_role_from_group_pb.js');
goog.object.extend(proto, identityd2_remove_role_from_group_pb);
var identityd2_add_subject_to_group_pb = require('../identityd2/add_subject_to_group_pb.js');
goog.object.extend(proto, identityd2_add_subject_to_group_pb);
var identityd2_remove_subject_from_group_pb = require('../identityd2/remove_subject_from_group_pb.js');
goog.object.extend(proto, identityd2_remove_subject_from_group_pb);
var identityd2_add_object_to_group_pb = require('../identityd2/add_object_to_group_pb.js');
goog.object.extend(proto, identityd2_add_object_to_group_pb);
var identityd2_remove_object_from_group_pb = require('../identityd2/remove_object_from_group_pb.js');
goog.object.extend(proto, identityd2_remove_object_from_group_pb);
var identityd2_create_credential_pb = require('../identityd2/create_credential_pb.js');
goog.object.extend(proto, identityd2_create_credential_pb);
var identityd2_delete_credential_pb = require('../identityd2/delete_credential_pb.js');
goog.object.extend(proto, identityd2_delete_credential_pb);
var identityd2_patch_credential_pb = require('../identityd2/patch_credential_pb.js');
goog.object.extend(proto, identityd2_patch_credential_pb);
var identityd2_get_credential_pb = require('../identityd2/get_credential_pb.js');
goog.object.extend(proto, identityd2_get_credential_pb);
var identityd2_list_credentials_pb = require('../identityd2/list_credentials_pb.js');
goog.object.extend(proto, identityd2_list_credentials_pb);
var identityd2_list_credentials_for_entity_pb = require('../identityd2/list_credentials_for_entity_pb.js');
goog.object.extend(proto, identityd2_list_credentials_for_entity_pb);
var identityd2_issue_token_by_credential_pb = require('../identityd2/issue_token_by_credential_pb.js');
goog.object.extend(proto, identityd2_issue_token_by_credential_pb);
var identityd2_issue_token_by_password_pb = require('../identityd2/issue_token_by_password_pb.js');
goog.object.extend(proto, identityd2_issue_token_by_password_pb);
var identityd2_issue_token_by_token_pb = require('../identityd2/issue_token_by_token_pb.js');
goog.object.extend(proto, identityd2_issue_token_by_token_pb);
var identityd2_revoke_token_pb = require('../identityd2/revoke_token_pb.js');
goog.object.extend(proto, identityd2_revoke_token_pb);
var identityd2_validate_token_pb = require('../identityd2/validate_token_pb.js');
goog.object.extend(proto, identityd2_validate_token_pb);
var identityd2_check_token_pb = require('../identityd2/check_token_pb.js');
goog.object.extend(proto, identityd2_check_token_pb);
var identityd2_authorize_token_pb = require('../identityd2/authorize_token_pb.js');
goog.object.extend(proto, identityd2_authorize_token_pb);
