exports.DevicedService = require('./DevicedService')
exports.EvaluatordService = require('./EvaluatordService')
exports.Identityd2Service = require('./Identityd2Service')
exports.MetaPlatformSrvService = require('./MtpdService')
exports.TagdService = require('./TagdService')
